# Application
base.url=https://demo.openmrs.org/openmrs
username=admin
password=Admin123

# Browser
browser=chrome
headless=false
#execution-env=local
execution-env=remote
# Waits
implicit.wait=10
explicit.wait=20
page.load.timeout=60

# Execution
environment=qa
parallel=true

# Reporting
screenshot.on.failure=true

# Grid
grid.url=http://localhost:4444/wd/hub

# Database
db.url=jdbc:mysql://localhost:3306/openmrs
db.username=root
db.password=root

# API
api.base.url=https://api.openmrs.org